var letterPool = ["a", "b", "c", "d", "e","f","g","h","i","j","k","l","m","n","o","p","q","r",
  "s","t","u","v","w","x","y","z","-"];

var wordPool = [
  {"name": "Afghanistan" , "code": "AF" , "popu": "29,121,286" , "area": "647,500" , "capital": "Kabul" , "region": "Asia"},
{"name": "Albania" , "code": "AL" , "popu": "2,986,952" , "area": "28,748" , "capital": "Tirana" , "region": "Europe"},
{"name": "Algeria" , "code": "DZ" , "popu": "34,586,184" , "area": "2,381,740" , "capital": "Algiers" , "region": "Africa"},
{"name": "American Samoa" , "code": "AS" , "popu": "57,881" , "area": "199" , "capital": "Pago Pago" , "region": "Oceania"},
{"name": "Andorra" , "code": "AD" , "popu": "84,000" , "area": "468" , "capital": "Andorra la Vella" , "region": "Europe"},
{"name": "Angola" , "code": "AO" , "popu": "13,068,161" , "area": "1,246,700" , "capital": "Luanda" , "region": "Africa"},
{"name": "Anguilla" , "code": "AI" , "popu": "13,254" , "area": "102" , "capital": "The Valley" , "region": "North America"},
{"name": "Antigua and Barbuda" , "code": "AG" , "popu": "86,754" , "area": "443" , "capital": "St. John's" , "region": "North America"},
{"name": "Argentina" , "code": "AR" , "popu": "41,343,201" , "area": "2,766,890" , "capital": "Buenos Aires" , "region": "South America"},
{"name": "Armenia" , "code": "AM" , "popu": "2,968,000" , "area": "29,800" , "capital": "Yerevan" , "region": "Asia"},
{"name": "Aruba" , "code": "AW" , "popu": "71,566" , "area": "193" , "capital": "Oranjestad" , "region": "North America"},
{"name": "Australia" , "code": "AU" , "popu": "21,515,754" , "area": "7,686,850" , "capital": "Canberra" , "region": "Oceania"},
{"name": "Austria" , "code": "AT" , "popu": "8,205,000" , "area": "83,858" , "capital": "Vienna" , "region": "Europe"},
{"name": "Azerbaijan" , "code": "AZ" , "popu": "8,303,512" , "area": "86,600" , "capital": "Baku" , "region": "Asia"},
{"name": "Bahamas" , "code": "BS" , "popu": "301,790" , "area": "13,940" , "capital": "Nassau" , "region": "North America"},
{"name": "Bahrain" , "code": "BH" , "popu": "738,004" , "area": "665" , "capital": "Manama" , "region": "Asia"},
{"name": "Bangladesh" , "code": "BD" , "popu": "156,118,464" , "area": "144,000" , "capital": "Dhaka" , "region": "Asia"},
{"name": "Barbados" , "code": "BB" , "popu": "285,653" , "area": "431" , "capital": "Bridgetown" , "region": "North America"},
{"name": "Belarus" , "code": "BY" , "popu": "9,685,000" , "area": "207,600" , "capital": "Minsk" , "region": "Europe"},
{"name": "Belgium" , "code": "BE" , "popu": "10,403,000" , "area": "30,510" , "capital": "Brussels" , "region": "Europe"},
{"name": "Belize" , "code": "BZ" , "popu": "314,522" , "area": "22,966" , "capital": "Belmopan" , "region": "North America"},
{"name": "Benin" , "code": "BJ" , "popu": "9,056,010" , "area": "112,620" , "capital": "Porto-Novo" , "region": "Africa"},
{"name": "Bermuda" , "code": "BM" , "popu": "65,365" , "area": "53" , "capital": "Hamilton" , "region": "North America"},
{"name": "Bhutan" , "code": "BT" , "popu": "699,847" , "area": "47,000" , "capital": "Thimphu" , "region": "Asia"},
{"name": "Bolivia" , "code": "BO" , "popu": "9,947,418" , "area": "1,098,580" , "capital": "Sucre" , "region": "South America"},
{"name": "Bosnia and Herzegovina" , "code": "BA" , "popu": "4,590,000" , "area": "51,129" , "capital": "Sarajevo" , "region": "Europe"},
{"name": "Botswana" , "code": "BW" , "popu": "2,029,307" , "area": "600,370" , "capital": "Gaborone" , "region": "Africa"},
{"name": "Brazil" , "code": "BR" , "popu": "201,103,330" , "area": "8,511,965" , "capital": "Brasilia" , "region": "South America"},
{"name": "British Indian Ocean Territory" , "code": "IO" , "popu": "4,000" , "area": "60" , "capital": "Diego Garcia" , "region": "Asia"},
{"name": "British Virgin Islands" , "code": "VG" , "popu": "21,730" , "area": "153" , "capital": "Road Town" , "region": "North America"},
{"name": "Brunei" , "code": "BN" , "popu": "395,027" , "area": "5,770" , "capital": "Bandar Seri Begawan" , "region": "Asia"},
{"name": "Bulgaria" , "code": "BG" , "popu": "7,148,785" , "area": "110,910" , "capital": "Sofia" , "region": "Europe"},
{"name": "Burkina Faso" , "code": "BF" , "popu": "16,241,811" , "area": "274,200" , "capital": "Ouagadougou" , "region": "Africa"},
{"name": "Burundi" , "code": "BI" , "popu": "9,863,117" , "area": "27,830" , "capital": "Bujumbura" , "region": "Africa"},
{"name": "Cambodia" , "code": "KH" , "popu": "14,453,680" , "area": "181,040" , "capital": "Phnom Penh" , "region": "Asia"},
{"name": "Cameroon" , "code": "CM" , "popu": "19,294,149" , "area": "475,440" , "capital": "Yaounde" , "region": "Africa"},
{"name": "Canada" , "code": "CA" , "popu": "33,679,000" , "area": "9,984,670" , "capital": "Ottawa" , "region": "North America"},
{"name": "Cape Verde" , "code": "CV" , "popu": "508,659" , "area": "4,033" , "capital": "Praia" , "region": "Africa"},
{"name": "Cayman Islands" , "code": "KY" , "popu": "44,270" , "area": "262" , "capital": "George Town" , "region": "North America"},
{"name": "Central African Republic" , "code": "CF" , "popu": "4,844,927" , "area": "622,984" , "capital": "Bangui" , "region": "Africa"},
{"name": "Chad" , "code": "TD" , "popu": "10,543,464" , "area": "1,284,000" , "capital": "N'Djamena" , "region": "Africa"},
{"name": "Chile" , "code": "CL" , "popu": "16,746,491" , "area": "756,950" , "capital": "Santiago" , "region": "South America"},
{"name": "China" , "code": "CN" , "popu": "1,330,044,000" , "area": "9,596,960" , "capital": "Beijing" , "region": "Asia"},
{"name": "Christmas Island" , "code": "CX" , "popu": "1,500" , "area": "135" , "capital": "Flying Fish Cove" , "region": "Oceania"},
{"name": "Cocos Islands" , "code": "CC" , "popu": "628" , "area": "14" , "capital": "West Island" , "region": "Asia"},
{"name": "Colombia" , "code": "CO" , "popu": "47,790,000" , "area": "1,138,910" , "capital": "Bogota" , "region": "South America"},
{"name": "Comoros" , "code": "KM" , "popu": "773,407" , "area": "2,170" , "capital": "Moroni" , "region": "Africa"},
{"name": "Cook Islands" , "code": "CK" , "popu": "21,388" , "area": "240" , "capital": "Avarua" , "region": "Oceania"},
{"name": "Costa Rica" , "code": "CR" , "popu": "4,516,220" , "area": "51,100" , "capital": "San Jose" , "region": "North America"},
{"name": "Croatia" , "code": "HR" , "popu": "4,284,889" , "area": "56,542" , "capital": "Zagreb" , "region": "Europe"},
{"name": "Cuba" , "code": "CU" , "popu": "11,423,000" , "area": "110,860" , "capital": "Havana" , "region": "North America"},
{"name": "Curacao" , "code": "CW" , "popu": "141,766" , "area": "444" , "capital": "Willemstad" , "region": "North America"},
{"name": "Cyprus" , "code": "CY" , "popu": "1,102,677" , "area": "9,250" , "capital": "Nicosia" , "region": "Europe"},
{"name": "Czechia" , "code": "CZ" , "popu": "10,476,000" , "area": "78,866" , "capital": "Prague" , "region": "Europe"},
{"name": "Democratic Republic of the Congo" , "code": "CD" , "popu": "70,916,439" , "area": "2,345,410" , "capital": "Kinshasa" , "region": "Africa"},
{"name": "Denmark" , "code": "DK" , "popu": "5,484,000" , "area": "43,094" , "capital": "Copenhagen" , "region": "Europe"},
{"name": "Djibouti" , "code": "DJ" , "popu": "740,528" , "area": "23,000" , "capital": "Djibouti" , "region": "Africa"},
{"name": "Dominica" , "code": "DM" , "popu": "72,813" , "area": "754" , "capital": "Roseau" , "region": "North America"},
{"name": "Dominican Republic" , "code": "DO" , "popu": "9,823,821" , "area": "48,730" , "capital": "Santo Domingo" , "region": "North America"},
{"name": "East Timor" , "code": "TL" , "popu": "1,154,625" , "area": "15,007" , "capital": "Dili" , "region": "Oceania"},
{"name": "Ecuador" , "code": "EC" , "popu": "14,790,608" , "area": "283,560" , "capital": "Quito" , "region": "South America"},
{"name": "Egypt" , "code": "EG" , "popu": "80,471,869" , "area": "1,001,450" , "capital": "Cairo" , "region": "Africa"},
{"name": "El Salvador" , "code": "SV" , "popu": "6,052,064" , "area": "21,040" , "capital": "San Salvador" , "region": "North America"},
{"name": "Equatorial Guinea" , "code": "GQ" , "popu": "1,014,999" , "area": "28,051" , "capital": "Malabo" , "region": "Africa"},
{"name": "Eritrea" , "code": "ER" , "popu": "5,792,984" , "area": "121,320" , "capital": "Asmara" , "region": "Africa"},
{"name": "Estonia" , "code": "EE" , "popu": "1,291,170" , "area": "45,226" , "capital": "Tallinn" , "region": "Europe"},
{"name": "Ethiopia" , "code": "ET" , "popu": "88,013,491" , "area": "1,127,127" , "capital": "Addis Ababa" , "region": "Africa"},
{"name": "Falkland Islands" , "code": "FK" , "popu": "2,638" , "area": "12,173" , "capital": "Stanley" , "region": "South America"},
{"name": "Faroe Islands" , "code": "FO" , "popu": "48,228" , "area": "1,399" , "capital": "Torshavn" , "region": "Europe"},
{"name": "Fiji" , "code": "FJ" , "popu": "875,983" , "area": "18,270" , "capital": "Suva" , "region": "Oceania"},
{"name": "Finland" , "code": "FI" , "popu": "5,244,000" , "area": "337,030" , "capital": "Helsinki" , "region": "Europe"},
{"name": "France" , "code": "FR" , "popu": "64,768,389" , "area": "547,030" , "capital": "Paris" , "region": "Europe"},
{"name": "French Guiana" , "code": "GF" , "popu": "195,506" , "area": "91,000" , "capital": "Cayenne" , "region": "South America"},
{"name": "French Polynesia" , "code": "PF" , "popu": "270,485" , "area": "4,167" , "capital": "Papeete" , "region": "Oceania"},
{"name": "Gabon" , "code": "GA" , "popu": "1,545,255" , "area": "267,667" , "capital": "Libreville" , "region": "Africa"},
{"name": "Gambia" , "code": "GM" , "popu": "1,593,256" , "area": "11,300" , "capital": "Banjul" , "region": "Africa"},
{"name": "Georgia" , "code": "GE" , "popu": "4,630,000" , "area": "69,700" , "capital": "Tbilisi" , "region": "Asia"},
{"name": "Germany" , "code": "DE" , "popu": "81,802,257" , "area": "357,021" , "capital": "Berlin" , "region": "Europe"},
{"name": "Ghana" , "code": "GH" , "popu": "24,339,838" , "area": "239,460" , "capital": "Accra" , "region": "Africa"},
{"name": "Gibraltar" , "code": "GI" , "popu": "27,884" , "area": "7" , "capital": "Gibraltar" , "region": "Europe"},
{"name": "Greece" , "code": "GR" , "popu": "11,000,000" , "area": "131,940" , "capital": "Athens" , "region": "Europe"},
{"name": "Greenland" , "code": "GL" , "popu": "56,375" , "area": "2,166,086" , "capital": "Nuuk" , "region": "North America"},
{"name": "Grenada" , "code": "GD" , "popu": "107,818" , "area": "344" , "capital": "St. George's" , "region": "North America"},
{"name": "Guadeloupe" , "code": "GP" , "popu": "443,000" , "area": "1,780" , "capital": "Basse-Terre" , "region": "North America"},
{"name": "Guam" , "code": "GU" , "popu": "159,358" , "area": "549" , "capital": "Hagatna" , "region": "Oceania"},
{"name": "Guatemala" , "code": "GT" , "popu": "13,550,440" , "area": "108,890" , "capital": "Guatemala City" , "region": "North America"},
{"name": "Guernsey" , "code": "GG" , "popu": "65,228" , "area": "78" , "capital": "St Peter Port" , "region": "Europe"},
{"name": "Guinea" , "code": "GN" , "popu": "10,324,025" , "area": "245,857" , "capital": "Conakry" , "region": "Africa"},
{"name": "Guinea-Bissau" , "code": "GW" , "popu": "1,565,126" , "area": "36,120" , "capital": "Bissau" , "region": "Africa"},
{"name": "Guyana" , "code": "GY" , "popu": "748,486" , "area": "214,970" , "capital": "Georgetown" , "region": "South America"},
{"name": "Haiti" , "code": "HT" , "popu": "9,648,924" , "area": "27,750" , "capital": "Port-au-Prince" , "region": "North America"},
{"name": "Honduras" , "code": "HN" , "popu": "7,989,415" , "area": "112,090" , "capital": "Tegucigalpa" , "region": "North America"},
{"name": "Hong Kong" , "code": "HK" , "popu": "6,898,686" , "area": "1,092" , "capital": "Hong Kong" , "region": "Asia"},
{"name": "Hungary" , "code": "HU" , "popu": "9,982,000" , "area": "93,030" , "capital": "Budapest" , "region": "Europe"},
{"name": "Iceland" , "code": "IS" , "popu": "308,910" , "area": "103,000" , "capital": "Reykjavik" , "region": "Europe"},
{"name": "India" , "code": "IN" , "popu": "1,173,108,018" , "area": "3,287,590" , "capital": "New Delhi" , "region": "Asia"},
{"name": "Indonesia" , "code": "ID" , "popu": "242,968,342" , "area": "1,919,440" , "capital": "Jakarta" , "region": "Asia"},
{"name": "Iran" , "code": "IR" , "popu": "76,923,300" , "area": "1,648,000" , "capital": "Tehran" , "region": "Asia"},
{"name": "Iraq" , "code": "IQ" , "popu": "29,671,605" , "area": "437,072" , "capital": "Baghdad" , "region": "Asia"},
{"name": "Ireland" , "code": "IE" , "popu": "4,622,917" , "area": "70,280" , "capital": "Dublin" , "region": "Europe"},
{"name": "Isle of Man" , "code": "IM" , "popu": "75,049" , "area": "572" , "capital": "Douglas" , "region": "Europe"},
{"name": "Israel" , "code": "IL" , "popu": "7,353,985" , "area": "20,770" , "capital": "Jerusalem" , "region": "Asia"},
{"name": "Italy" , "code": "IT" , "popu": "60,340,328" , "area": "301,230" , "capital": "Rome" , "region": "Europe"},
{"name": "Ivory Coast" , "code": "CI" , "popu": "21,058,798" , "area": "322,460" , "capital": "Yamoussoukro" , "region": "Africa"},
{"name": "Jamaica" , "code": "JM" , "popu": "2,847,232" , "area": "10,991" , "capital": "Kingston" , "region": "North America"},
{"name": "Japan" , "code": "JP" , "popu": "127,288,000" , "area": "377,835" , "capital": "Tokyo" , "region": "Asia"},
{"name": "Jersey" , "code": "JE" , "popu": "90,812" , "area": "116" , "capital": "Saint Helier" , "region": "Europe"},
{"name": "Jordan" , "code": "JO" , "popu": "6,407,085" , "area": "92,300" , "capital": "Amman" , "region": "Asia"},
{"name": "Kazakhstan" , "code": "KZ" , "popu": "15,340,000" , "area": "2,717,300" , "capital": "Astana" , "region": "Asia"},
{"name": "Kenya" , "code": "KE" , "popu": "40,046,566" , "area": "582,650" , "capital": "Nairobi" , "region": "Africa"},
{"name": "Kiribati" , "code": "KI" , "popu": "92,533" , "area": "811" , "capital": "Tarawa" , "region": "Oceania"},
{"name": "Kosovo" , "code": "XK" , "popu": "1,800,000" , "area": "10,908" , "capital": "Pristina" , "region": "Europe"},
{"name": "Kuwait" , "code": "KW" , "popu": "2,789,132" , "area": "17,820" , "capital": "Kuwait City" , "region": "Asia"},
{"name": "Kyrgyzstan" , "code": "KG" , "popu": "5,776,500" , "area": "198,500" , "capital": "Bishkek" , "region": "Asia"},
{"name": "Laos" , "code": "LA" , "popu": "6,368,162" , "area": "236,800" , "capital": "Vientiane" , "region": "Asia"},
{"name": "Latvia" , "code": "LV" , "popu": "2,217,969" , "area": "64,589" , "capital": "Riga" , "region": "Europe"},
{"name": "Lebanon" , "code": "LB" , "popu": "4,125,247" , "area": "10,400" , "capital": "Beirut" , "region": "Asia"},
{"name": "Lesotho" , "code": "LS" , "popu": "1,919,552" , "area": "30,355" , "capital": "Maseru" , "region": "Africa"},
{"name": "Liberia" , "code": "LR" , "popu": "3,685,076" , "area": "111,370" , "capital": "Monrovia" , "region": "Africa"},
{"name": "Libya" , "code": "LY" , "popu": "6,461,454" , "area": "1,759,540" , "capital": "Tripoli" , "region": "Africa"},
{"name": "Liechtenstein" , "code": "LI" , "popu": "35,000" , "area": "160" , "capital": "Vaduz" , "region": "Europe"},
{"name": "Lithuania" , "code": "LT" , "popu": "2,944,459" , "area": "65,200" , "capital": "Vilnius" , "region": "Europe"},
{"name": "Luxembourg" , "code": "LU" , "popu": "497,538" , "area": "2,586" , "capital": "Luxembourg" , "region": "Europe"},
{"name": "Macao" , "code": "MO" , "popu": "449,198" , "area": "254" , "capital": "Macao" , "region": "Asia"},
{"name": "Macedonia" , "code": "MK" , "popu": "2,062,294" , "area": "25,333" , "capital": "Skopje" , "region": "Europe"},
{"name": "Madagascar" , "code": "MG" , "popu": "21,281,844" , "area": "587,040" , "capital": "Antananarivo" , "region": "Africa"},
{"name": "Malawi" , "code": "MW" , "popu": "15,447,500" , "area": "118,480" , "capital": "Lilongwe" , "region": "Africa"},
{"name": "Malaysia" , "code": "MY" , "popu": "28,274,729" , "area": "329,750" , "capital": "Kuala Lumpur" , "region": "Asia"},
{"name": "Maldives" , "code": "MV" , "popu": "395,650" , "area": "300" , "capital": "Male" , "region": "Asia"},
{"name": "Mali" , "code": "ML" , "popu": "13,796,354" , "area": "1,240,000" , "capital": "Bamako" , "region": "Africa"},
{"name": "Malta" , "code": "MT" , "popu": "403,000" , "area": "316" , "capital": "Valletta" , "region": "Europe"},
{"name": "Marshall Islands" , "code": "MH" , "popu": "65,859" , "area": "181" , "capital": "Majuro" , "region": "Oceania"},
{"name": "Martinique" , "code": "MQ" , "popu": "432,900" , "area": "1,100" , "capital": "Fort-de-France" , "region": "North America"},
{"name": "Mauritania" , "code": "MR" , "popu": "3,205,060" , "area": "1,030,700" , "capital": "Nouakchott" , "region": "Africa"},
{"name": "Mauritius" , "code": "MU" , "popu": "1,294,104" , "area": "2,040" , "capital": "Port Louis" , "region": "Africa"},
{"name": "Mayotte" , "code": "YT" , "popu": "159,042" , "area": "374" , "capital": "Mamoudzou" , "region": "Africa"},
{"name": "Mexico" , "code": "MX" , "popu": "112,468,855" , "area": "1,972,550" , "capital": "Mexico City" , "region": "North America"},
{"name": "Micronesia" , "code": "FM" , "popu": "107,708" , "area": "702" , "capital": "Palikir" , "region": "Oceania"},
{"name": "Moldova" , "code": "MD" , "popu": "4,324,000" , "area": "33,843" , "capital": "Chisinau" , "region": "Europe"},
{"name": "Monaco" , "code": "MC" , "popu": "32,965" , "area": "2" , "capital": "Monaco" , "region": "Europe"},
{"name": "Mongolia" , "code": "MN" , "popu": "3,086,918" , "area": "1,565,000" , "capital": "Ulan Bator" , "region": "Asia"},
{"name": "Montenegro" , "code": "ME" , "popu": "666,730" , "area": "14,026" , "capital": "Podgorica" , "region": "Europe"},
{"name": "Montserrat" , "code": "MS" , "popu": "9,341" , "area": "102" , "capital": "Plymouth" , "region": "North America"},
{"name": "Morocco" , "code": "MA" , "popu": "33,848,242" , "area": "446,550" , "capital": "Rabat" , "region": "Africa"},
{"name": "Mozambique" , "code": "MZ" , "popu": "22,061,451" , "area": "801,590" , "capital": "Maputo" , "region": "Africa"},
{"name": "Myanmar" , "code": "MM" , "popu": "53,414,374" , "area": "678,500" , "capital": "Nay Pyi Taw" , "region": "Asia"},
{"name": "Namibia" , "code": "NA" , "popu": "2,128,471" , "area": "825,418" , "capital": "Windhoek" , "region": "Africa"},
{"name": "Nauru" , "code": "NR" , "popu": "10,065" , "area": "21" , "capital": "Yaren" , "region": "Oceania"},
{"name": "Nepal" , "code": "NP" , "popu": "28,951,852" , "area": "140,800" , "capital": "Kathmandu" , "region": "Asia"},
{"name": "Netherlands" , "code": "NL" , "popu": "16,645,000" , "area": "41,526" , "capital": "Amsterdam" , "region": "Europe"},
{"name": "Netherlands Antilles" , "code": "AN" , "popu": "300,000" , "area": "960" , "capital": "Willemstad" , "region": "North America"},
{"name": "New Caledonia" , "code": "NC" , "popu": "216,494" , "area": "19,060" , "capital": "Noumea" , "region": "Oceania"},
{"name": "New Zealand" , "code": "NZ" , "popu": "4,252,277" , "area": "268,680" , "capital": "Wellington" , "region": "Oceania"},
{"name": "Nicaragua" , "code": "NI" , "popu": "5,995,928" , "area": "129,494" , "capital": "Managua" , "region": "North America"},
{"name": "Niger" , "code": "NE" , "popu": "15,878,271" , "area": "1,267,000" , "capital": "Niamey" , "region": "Africa"},
{"name": "Nigeria" , "code": "NG" , "popu": "154,000,000" , "area": "923,768" , "capital": "Abuja" , "region": "Africa"},
{"name": "Niue" , "code": "NU" , "popu": "2,166" , "area": "260" , "capital": "Alofi" , "region": "Oceania"},
{"name": "Norfolk Island" , "code": "NF" , "popu": "1,828" , "area": "35" , "capital": "Kingston" , "region": "Oceania"},
{"name": "North Korea" , "code": "KP" , "popu": "22,912,177" , "area": "120,540" , "capital": "Pyongyang" , "region": "Asia"},
{"name": "Northern Mariana Islands" , "code": "MP" , "popu": "53,883" , "area": "477" , "capital": "Saipan" , "region": "Oceania"},
{"name": "Norway" , "code": "NO" , "popu": "5,009,150" , "area": "324,220" , "capital": "Oslo" , "region": "Europe"},
{"name": "Oman" , "code": "OM" , "popu": "2,967,717" , "area": "212,460" , "capital": "Muscat" , "region": "Asia"},
{"name": "Pakistan" , "code": "PK" , "popu": "184,404,791" , "area": "803,940" , "capital": "Islamabad" , "region": "Asia"},
{"name": "Palau" , "code": "PW" , "popu": "19,907" , "area": "458" , "capital": "Melekeok" , "region": "Oceania"},
{"name": "Palestine" , "code": "PS" , "popu": "3,800,000" , "area": "5,970" , "capital": "East Jerusalem" , "region": "Asia"},
{"name": "Panama" , "code": "PA" , "popu": "3,410,676" , "area": "78,200" , "capital": "Panama City" , "region": "North America"},
{"name": "Papua New Guinea" , "code": "PG" , "popu": "6,064,515" , "area": "462,840" , "capital": "Port Moresby" , "region": "Oceania"},
{"name": "Paraguay" , "code": "PY" , "popu": "6,375,830" , "area": "406,750" , "capital": "Asuncion" , "region": "South America"},
{"name": "Peru" , "code": "PE" , "popu": "29,907,003" , "area": "1,285,220" , "capital": "Lima" , "region": "South America"},
{"name": "Philippines" , "code": "PH" , "popu": "99,900,177" , "area": "300,000" , "capital": "Manila" , "region": "Asia"},
{"name": "Pitcairn Islands" , "code": "PN" , "popu": "46" , "area": "47" , "capital": "Adamstown" , "region": "Oceania"},
{"name": "Poland" , "code": "PL" , "popu": "38,500,000" , "area": "312,685" , "capital": "Warsaw" , "region": "Europe"},
{"name": "Portugal" , "code": "PT" , "popu": "10,676,000" , "area": "92,391" , "capital": "Lisbon" , "region": "Europe"},
{"name": "Puerto Rico" , "code": "PR" , "popu": "3,916,632" , "area": "9,104" , "capital": "San Juan" , "region": "North America"},
{"name": "Qatar" , "code": "QA" , "popu": "840,926" , "area": "11,437" , "capital": "Doha" , "region": "Asia"},
{"name": "Republic of the Congo" , "code": "CG" , "popu": "3,039,126" , "area": "342,000" , "capital": "Brazzaville" , "region": "Africa"},
{"name": "Romania" , "code": "RO" , "popu": "21,959,278" , "area": "237,500" , "capital": "Bucharest" , "region": "Europe"},
{"name": "Russia" , "code": "RU" , "popu": "140,702,000" , "area": "17,100,000" , "capital": "Moscow" , "region": "Europe"},
{"name": "Rwanda" , "code": "RW" , "popu": "11,055,976" , "area": "26,338" , "capital": "Kigali" , "region": "Africa"},
{"name": "Reunion" , "code": "RE" , "popu": "776,948" , "area": "2,517" , "capital": "Saint-Denis" , "region": "Africa"},
{"name": "Saint Barthelemy" , "code": "BL" , "popu": "8,450" , "area": "21" , "capital": "Gustavia" , "region": "North America"},
{"name": "Saint Helena" , "code": "SH" , "popu": "7,460" , "area": "410" , "capital": "Jamestown" , "region": "Africa"},
{"name": "Saint Kitts and Nevis" , "code": "KN" , "popu": "51,134" , "area": "261" , "capital": "Basseterre" , "region": "North America"},
{"name": "Saint Lucia" , "code": "LC" , "popu": "160,922" , "area": "616" , "capital": "Castries" , "region": "North America"},
{"name": "Saint Martin" , "code": "MF" , "popu": "35,925" , "area": "53" , "capital": "Marigot" , "region": "North America"},
{"name": "Saint Pierre and Miquelon" , "code": "PM" , "popu": "7,012" , "area": "242" , "capital": "Saint-Pierre" , "region": "North America"},
{"name": "Saint Vincent and the Grenadines" , "code": "VC" , "popu": "104,217" , "area": "389" , "capital": "Kingstown" , "region": "North America"},
{"name": "Samoa" , "code": "WS" , "popu": "192,001" , "area": "2,944" , "capital": "Apia" , "region": "Oceania"},
{"name": "San Marino" , "code": "SM" , "popu": "31,477" , "area": "61" , "capital": "San Marino" , "region": "Europe"},
{"name": "Saudi Arabia" , "code": "SA" , "popu": "25,731,776" , "area": "1,960,582" , "capital": "Riyadh" , "region": "Asia"},
{"name": "Senegal" , "code": "SN" , "popu": "12,323,252" , "area": "196,190" , "capital": "Dakar" , "region": "Africa"},
{"name": "Serbia" , "code": "RS" , "popu": "7,344,847" , "area": "88,361" , "capital": "Belgrade" , "region": "Europe"},
{"name": "Serbia and Montenegro" , "code": "CS" , "popu": "10,829,175" , "area": "102,350" , "capital": "Belgrade" , "region": "Europe"},
{"name": "Seychelles" , "code": "SC" , "popu": "88,340" , "area": "455" , "capital": "Victoria" , "region": "Africa"},
{"name": "Sierra Leone" , "code": "SL" , "popu": "5,245,695" , "area": "71,740" , "capital": "Freetown" , "region": "Africa"},
{"name": "Singapore" , "code": "SG" , "popu": "4,701,069" , "area": "693" , "capital": "Singapore" , "region": "Asia"},
{"name": "Sint Maarten" , "code": "SX" , "popu": "37,429" , "area": "21" , "capital": "Philipsburg" , "region": "North America"},
{"name": "Slovakia" , "code": "SK" , "popu": "5,455,000" , "area": "48,845" , "capital": "Bratislava" , "region": "Europe"},
{"name": "Slovenia" , "code": "SI" , "popu": "2,007,000" , "area": "20,273" , "capital": "Ljubljana" , "region": "Europe"},
{"name": "Solomon Islands" , "code": "SB" , "popu": "559,198" , "area": "28,450" , "capital": "Honiara" , "region": "Oceania"},
{"name": "Somalia" , "code": "SO" , "popu": "10,112,453" , "area": "637,657" , "capital": "Mogadishu" , "region": "Africa"},
{"name": "South Africa" , "code": "ZA" , "popu": "49,000,000" , "area": "1,219,912" , "capital": "Pretoria" , "region": "Africa"},
{"name": "South Korea" , "code": "KR" , "popu": "48,422,644" , "area": "98,480" , "capital": "Seoul" , "region": "Asia"},
{"name": "South Sudan" , "code": "SS" , "popu": "8,260,490" , "area": "644,329" , "capital": "Juba" , "region": "Africa"},
{"name": "Spain" , "code": "ES" , "popu": "46,505,963" , "area": "504,782" , "capital": "Madrid" , "region": "Europe"},
{"name": "Sri Lanka" , "code": "LK" , "popu": "21,513,990" , "area": "65,610" , "capital": "Colombo" , "region": "Asia"},
{"name": "Sudan" , "code": "SD" , "popu": "35,000,000" , "area": "1,861,484" , "capital": "Khartoum" , "region": "Africa"},
{"name": "Suriname" , "code": "SR" , "popu": "492,829" , "area": "163,270" , "capital": "Paramaribo" , "region": "South America"},
{"name": "Svalbard and Jan Mayen" , "code": "SJ" , "popu": "2,550" , "area": "62,049" , "capital": "Longyearbyen" , "region": "Europe"},
{"name": "Swaziland" , "code": "SZ" , "popu": "1,354,051" , "area": "17,363" , "capital": "Mbabane" , "region": "Africa"},
{"name": "Sweden" , "code": "SE" , "popu": "9,828,655" , "area": "449,964" , "capital": "Stockholm" , "region": "Europe"},
{"name": "Switzerland" , "code": "CH" , "popu": "7,581,000" , "area": "41,290" , "capital": "Bern" , "region": "Europe"},
{"name": "Syria" , "code": "SY" , "popu": "22,198,110" , "area": "185,180" , "capital": "Damascus" , "region": "Asia"},
{"name": "Sao Tome and Principe" , "code": "ST" , "popu": "175,808" , "area": "1,001" , "capital": "Sao Tome" , "region": "Africa"},
{"name": "Taiwan" , "code": "TW" , "popu": "22,894,384" , "area": "35,980" , "capital": "Taipei" , "region": "Asia"},
{"name": "Tajikistan" , "code": "TJ" , "popu": "7,487,489" , "area": "143,100" , "capital": "Dushanbe" , "region": "Asia"},
{"name": "Tanzania" , "code": "TZ" , "popu": "41,892,895" , "area": "945,087" , "capital": "Dodoma" , "region": "Africa"},
{"name": "Thailand" , "code": "TH" , "popu": "67,089,500" , "area": "514,000" , "capital": "Bangkok" , "region": "Asia"},
{"name": "Togo" , "code": "TG" , "popu": "6,587,239" , "area": "56,785" , "capital": "Lome" , "region": "Africa"},
{"name": "Tonga" , "code": "TO" , "popu": "122,580" , "area": "748" , "capital": "Nuku'alofa" , "region": "Oceania"},
{"name": "Trinidad and Tobago" , "code": "TT" , "popu": "1,328,019" , "area": "5,128" , "capital": "Port of Spain" , "region": "North America"},
{"name": "Tunisia" , "code": "TN" , "popu": "10,589,025" , "area": "163,610" , "capital": "Tunis" , "region": "Africa"},
{"name": "Turkey" , "code": "TR" , "popu": "77,804,122" , "area": "780,580" , "capital": "Ankara" , "region": "Asia"},
{"name": "Turkmenistan" , "code": "TM" , "popu": "4,940,916" , "area": "488,100" , "capital": "Ashgabat" , "region": "Asia"},
{"name": "Turks and Caicos Islands" , "code": "TC" , "popu": "20,556" , "area": "430" , "capital": "Cockburn Town" , "region": "North America"},
{"name": "Tuvalu" , "code": "TV" , "popu": "10,472" , "area": "26" , "capital": "Funafuti" , "region": "Oceania"},
{"name": "Uganda" , "code": "UG" , "popu": "33,398,682" , "area": "236,040" , "capital": "Kampala" , "region": "Africa"},
{"name": "Ukraine" , "code": "UA" , "popu": "45,415,596" , "area": "603,700" , "capital": "Kiev" , "region": "Europe"},
{"name": "United Arab Emirates" , "code": "AE" , "popu": "4,975,593" , "area": "82,880" , "capital": "Abu Dhabi" , "region": "Asia"},
{"name": "United Kingdom" , "code": "GB" , "popu": "62,348,447" , "area": "244,820" , "capital": "London" , "region": "Europe"},
{"name": "United States" , "code": "US" , "popu": "310,232,863" , "area": "9,629,091" , "capital": "Washington" , "region": "North America"},
{"name": "Uruguay" , "code": "UY" , "popu": "3,477,000" , "area": "176,220" , "capital": "Montevideo" , "region": "South America"},
{"name": "Uzbekistan" , "code": "UZ" , "popu": "27,865,738" , "area": "447,400" , "capital": "Tashkent" , "region": "Asia"},
{"name": "Vanuatu" , "code": "VU" , "popu": "221,552" , "area": "12,200" , "capital": "Port Vila" , "region": "Oceania"},
{"name": "Vatican City" , "code": "VA" , "popu": "921" , "area": "0" , "capital": "Vatican City" , "region": "Europe"},
{"name": "Venezuela" , "code": "VE" , "popu": "27,223,228" , "area": "912,050" , "capital": "Caracas" , "region": "South America"},
{"name": "Vietnam" , "code": "VN" , "popu": "89,571,130" , "area": "329,560" , "capital": "Hanoi" , "region": "Asia"},
{"name": "Wallis and Futuna" , "code": "WF" , "popu": "16,025" , "area": "274" , "capital": "Mata Utu" , "region": "Oceania"},
{"name": "Western Sahara" , "code": "EH" , "popu": "273,008" , "area": "266,000" , "capital": "El-Aaiun" , "region": "Africa"},
{"name": "Yemen" , "code": "YE" , "popu": "23,495,361" , "area": "527,970" , "capital": "Sanaa" , "region": "Asia"},
{"name": "Zambia" , "code": "ZM" , "popu": "13,460,305" , "area": "752,614" , "capital": "Lusaka" , "region": "Africa"},
{"name": "Zimbabwe" , "code": "ZW" , "popu": "13,061,000" , "area": "390,580" , "capital": "Harare" , "region": "Africa"},
];
